language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install
  - yarn build

script:
  - yarn test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  keep-history: true
  local-dir: content/.vuepress/dist
  on:
    branch: master
